Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -51,7 +51,17 @@ jobs:
       uses: rbhadti94/apache-jmeter-action@v0.5.0
       with:
         testFilePath: tests/1user_pr.jmx
-        args: "--loglevel INFO"
+
+    - name: Check JMeter Test Results
+      run: |
+        # Check if any JMeter tests failed
+        if grep -q "Err:" test.jtl; then
+          echo "Some JMeter tests failed"
+          exit 1
+        else
+          echo "All JMeter tests passed"
+          exit 0
+        fi
 
     - name: Tear down Docker Compose
       run: docker-compose down
